const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
let state={name:"AGNEY",style:"balanced",season:1,round:1,points:0,rep:62,funds:8,bike:{engine:72,aero:54,chassis:81,electronics:63,reliability:71},choice:"push"};
const circuits=["QATAR","PORTIMAO","JEREZ","LE MANS","MUGELLO","ASSEN","SACHSENRING","SILVERSTONE","MISANO","MOTEGI","PHILLIP ISLAND","VALENCIA"];
const riders=[["#93","MARC","FACTORY GP"],["#63","LUCA","FACTORY GP"],["#89","JORGE","FACTORY GP"],["#10","ALEX","FACTORY GP"],["#12","FABIO","FACTORY GP"],["#21","FRANCO","SATELLITE GP"],["#27","YOU","SATELLITE GP"],["#5","JOAN","SATELLITE GP"],["#41","BRAD","SATELLITE GP"],["#72","MARCO","SATELLITE GP"]];
const devNames={engine:["ENGINE","Top speed & acceleration"],aero:["AERO","High-speed stability & corner entry"],chassis:["CHASSIS","Turning & rear grip"],electronics:["ELECTRONICS","Traction, launch & braking control"],reliability:["RELIABILITY","Mechanical resilience"]};
function save(){try{localStorage.setItem("gpxMotoCareer",JSON.stringify(state))}catch(e){}}
function load(){try{const x=JSON.parse(localStorage.getItem("gpxMotoCareer"));if(x)state=x}catch(e){}}
function bikeRating(){return Math.round(Object.values(state.bike).reduce((a,b)=>a+b,0)/5)}
function money(){return "€"+state.funds.toFixed(1)+"M"}
function feed(title,text){const d=document.createElement("div");d.className="feed-item";d.innerHTML="<b>"+title+"</b><span>"+text+"</span>";$("#feed").prepend(d)}
function render(){load();$("#season").textContent=state.season;$("#welcome").textContent="WELCOME, "+state.name;$("#teamLine").textContent=(state.rep>80?"FACTORY TEAM":"SATELLITE TEAM")+" · MOTOGP";$("#nextCircuit").textContent=circuits[(state.round-1)%circuits.length];$("#roundText").textContent="ROUND "+state.round+" / 12";$("#points").textContent=state.points;$("#rep").textContent=state.rep;$("#bikeRating").textContent=bikeRating();$("#funds").textContent=money();$("#devFunds").textContent=state.funds.toFixed(1);$("#totalRating").textContent="BIKE RATING "+bikeRating();$("#profileName").textContent=state.name;$("#profileStyle").textContent=state.style.toUpperCase()+" RIDER";$("#pace").textContent=state.style==="aggressive"?71:68;$("#craft").textContent=state.style==="smooth"?69:65;$("#consistency").textContent=state.style==="smooth"?72:67;$("#rank").textContent=state.rep>85?"FACTORY ACE":state.rep>70?"CONTENDER":"ROOKIE";renderDev();renderStandings()}
function start(){state.name=($("#riderName").value||"AGNEY").trim().toUpperCase();state.style=$("#styleSelect").value;state.season=1;state.round=1;state.points=0;state.rep=62;state.funds=8;state.bike={engine:72,aero:54,chassis:81,electronics:63,reliability:71};save();$("#careerSetup").classList.add("hidden");$("#game").classList.remove("hidden");render();feed("CONTRACT SIGNED","Welcome to the satellite garage. Your first target is a points finish.");window.scrollTo({top:0,behavior:"smooth"})}
function renderDev(){const g=$("#devGrid");g.innerHTML="";Object.entries(devNames).forEach(([key,v])=>{const level=state.bike[key],c=document.createElement("article");c.className="dev-card";c.innerHTML='<div class="panel-head"><span>ENGINEERING</span><span>'+String(level).padStart(2,"0")+'/100</span></div><h3>'+v[0]+'</h3><p>'+v[1]+'</p><div class="dev-level">'+level+'</div><div class="bar"><i style="width:'+level+'%"></i></div><button class="upgrade" data-dev="'+key+'" '+(state.funds<1||level>=99?"disabled":"")+'>UPGRADE · €1.0M</button>';g.appendChild(c)})}
function renderStandings(){let arr=riders.map((r,i)=>({r,pts:Math.max(0,70-i*7+((state.round-1)*[9,7,6,5,4,3,2,1,0,0][i]))}));arr.find(x=>x.r[1]==="YOU").pts=state.points;arr.sort((a,b)=>b.pts-a.pts);$("#standingRound").textContent=Math.max(1,state.round-1);$("#standingsRows").innerHTML=arr.map((x,i)=>'<div class="table-row '+(x.r[1]==="YOU"?"me":"")+'"><span class="rank">'+(i+1).toString().padStart(2,"0")+'</span><span><b>'+x.r[0]+'</b> '+x.r[1]+'</span><span>'+x.r[2]+'</span><span>'+x.pts+'</span></div>').join("")}
function race(){const base=bikeRating(),styleBonus=state.style==="aggressive"?2:state.style==="smooth"?1:0,choice=state.choice;let grid=Math.max(3,Math.min(20,22-Math.round(base/8)-Math.round(state.rep/15)-styleBonus));if(choice==="conserve")grid+=2;if(choice==="push")grid-=1;$("#gridPos").textContent="P"+grid;$("#raceStatus").textContent="RESULT";$("#paceText").textContent=choice==="push"?"MAX ATTACK":choice==="conserve"?"TYRE SAVE":"RACE PACE";let finish=grid+(Math.floor(Math.random()*7)-3);if(state.bike.reliability<55&&Math.random()<.16)finish=21;finish=Math.max(1,Math.min(20,finish));const pts=[25,20,16,13,11,10,9,8,7,6,5,4,3,2,1][finish-1]||0;state.points+=pts;state.rep=Math.max(1,Math.min(100,state.rep+(finish<=3?5:finish<=10?2:-1)));state.funds=Math.max(0,state.funds+pts*.06);if(finish===21){$("#raceResult").innerHTML="<h3>DNF — MECHANICAL</h3><p>The bike did not make the chequered flag. Reliability development should be your next priority.</p>"}else{$("#raceResult").innerHTML="<h3>FINISHED P"+finish+" — "+pts+" POINTS</h3><p>"+(finish<=3?"Podium momentum. Your reputation is rising.":finish<=10?"Solid points finish. The team is encouraged.":"A difficult Sunday. The engineering department needs answers.")+"</p>"}$("#raceResult").classList.remove("hidden");feed("ROUND "+state.round,"Finished P"+(finish===21?"DNF":finish)+" at "+circuits[(state.round-1)%circuits.length]+".");state.round++;if(state.round>12){state.season++;state.round=1;feed("SEASON COMPLETE","A new championship season begins. Contract negotiations are open.")}save();render()}
$("#startCareer").addEventListener("click",start);$("#resetBtn").addEventListener("click",()=>{if(confirm("Start a new career? Your current save will be erased.")){localStorage.removeItem("gpxMotoCareer");location.reload()}});
$$(".tab").forEach(b=>b.addEventListener("click",()=>{$$(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".view").forEach(v=>v.classList.add("hidden"));$("#"+b.dataset.view).classList.remove("hidden")}));
$$(".choice").forEach(b=>b.addEventListener("click",()=>{$$(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.choice=b.dataset.choice}));
$("#runRace").addEventListener("click",race);
$("#devGrid").addEventListener("click",e=>{const b=e.target.closest(".upgrade");if(!b)return;const k=b.dataset.dev;if(state.funds>=1&&state.bike[k]<99){state.funds-=1;state.bike[k]=Math.min(99,state.bike[k]+Math.floor(3+Math.random()*5));feed("DEVELOPMENT COMPLETE",devNames[k][0]+" package installed. Bike rating updated.");save();render()}});
load();if(localStorage.getItem("gpxMotoCareer")){$("#careerSetup").classList.add("hidden");$("#game").classList.remove("hidden");render()}